### PR TITLE
Fix/coin gecko cors errors

### PR DESCRIPTION
**Pull request by roienatan**
- One coin gecko call for multiple staking tokens
- Use `no-cache` fetch policy for vaults data instead of deep cloning the retrieved data
- More minor updates

### CODE REVIEW

**Comment by leviyehonatan** [comment]
@roienatan  so the usage of multiple keys in one call had a clear impact on loading time to the first page which uses exactly that, and that's very good. now about the cache, in our case no-cache has no influence as it is used when updating data, or re-querying the data, but since you use the redux to store the data its simply never used anyhow as far as i can see

**Comment by leviyehonatan** [comment]
@roienatan  looking at the network log i can see a request ```https://api.coingecko.com/api/v3/simple/token_price/ethereum?contract_addresses=&vs_currencies=usd``` can we try and eliminate this one extra unneeded request?

**Comment by roienatan** [comment]
> @roienatan  looking at the network log i can see a request ```https://api.coingecko.com/api/v3/simple/token_price/ethereum?contract_addresses=&vs_currencies=usd``` can we try and eliminate this one extra unneeded request?

Will take a look on that

**Comment by roienatan** [comment]
> @roienatan looking at the network log i can see a request `https://api.coingecko.com/api/v3/simple/token_price/ethereum?contract_addresses=&vs_currencies=usd` can we try and eliminate this one extra unneeded request?

@leviyehonatan I'm pretty sure it's the call in line 120 which is necessary to get the rewards token (hats token) price.

**Review by leviyehonatan — APPROVED** [review]
looks good to me

**Pull request merged**
